ajcl_ims/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),]

compliancehub/urls.py
import os
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.views.generic import TemplateView

# Up two folders to serve "docs" content
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS_ROOT = os.path.join(BASE_DIR, 'docs')

urlpatterns = [
    path('', TemplateView.as_view(template_name='home/main.html')),
    path('jhpl-ims/', include('jhpl_ims.urls')),
    path('ajcl-ims/', include('ajcl_ims.urls')),
    path("admin/", admin.site.urls),

    path('accounts/', include('django.contrib.auth.urls')),

    re_path(r'^docs/(?P<path>.*)$', serve,
            {'document_root': DOCS_ROOT, 'show_indexes': True},
            name='docs_path'
            ),

]

jhpl_ims/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = 'jhpl_ims'

urlpatterns = [

    path('', views.index.as_view(), name='index'),
    path('procedures/<int:pk>', views.procedures.as_view(), name='procedures'),
    path('master-list/<int:pk>/update', views.MasterUpdateView.as_view(
        success_url=reverse_lazy('jhpl_ims:index')), name='jhplmaster_update'),
    path('sop/<int:pk>/comment', views.NotesCreateView.as_view(), name='comment_create'),
    path('comment/<int:pk>/delete', views.NotesDeleteView.as_view(success_url=reverse_lazy('jhpl_ims:index')), name='comment_delete'),
    path('incidents', views.IncidentListView.as_view(), name='incident_list'),
    path('incidentdetail/<int:pk>', views.IncidentDetailView.as_view(), name='incident_detail'),
    path('incident/<int:pk>/delete', views.IncidentDeleteView.as_view(success_url=reverse_lazy('jhpl_ims:incident_list')), name='incident_delete'),
    path('incident/create', views.IncidentCreateView.as_view(), name='incident_create'),
    path('incident_picture/<int:pk>', views.stream_file, name='incident_picture'),
    path('incident/<int:pk>/update',views.IncidentUpdateView.as_view(success_url=reverse_lazy('jhpl_ims:incident_list')), name='incident_update'),
    
    
]

jhpl_ims/models.py
from django.db import models
from django.conf import settings

class doc_controller(models.Model):
    doc_controller_id = models.AutoField(primary_key=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    name = models.CharField(max_length=100, null=True, blank=True)
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class jhpl_ims_masterlist(models.Model):
    STATUS_SELECT = [
        ("Active", "Active"),
        ("Obsolete", "Obsolete"),
        ("InProcess", "InProcess"),
        ]
    ims_masterlist_id = models.AutoField(primary_key=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    doc_num = models.CharField(max_length=200, null = False, blank= False)
    doc_title = models.CharField(max_length=200, null=True, blank=True)
    rev_num = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    issue_date = models.DateField(null=True, blank=True)
    status = models.CharField(max_length=9, choices=STATUS_SELECT)
    reviewed_by = models.ForeignKey("doc_controller", on_delete=models.CASCADE, related_name="jhpl_reviewed_by",null= True,blank = True)
    reviewed_date = models.DateField(null=True, blank=True)
    approved_by = models.ForeignKey("doc_controller", on_delete=models.CASCADE, related_name="jhpl_approved_by",null= True,blank= True)
    approved_date = models.DateField(null=True, blank=True)
    control_copy_num = models.IntegerField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.doc_title


class notes(models.Model):
    notes_id = models.AutoField(primary_key=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    large_text_body = models.TextField()
    jhpl_ims_masterlist_key = models.ForeignKey("jhpl_ims_masterlist", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.large_text_body


class incident(models.Model):
    incident_id = models.AutoField(primary_key=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,
                              on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now=True)
    incident_datetime = models.DateTimeField()
    people_involved = models.TextField()
    incident_location = models.CharField(
        max_length=200, null=False, blank=False)
    incident_description = models.TextField()
    incident_witness = models.CharField(max_length=200, null=True, blank=True)
    incident_outcome = models.BooleanField(default=False)
    picture = models.BinaryField(null=True, blank=True, editable=True)
    content_type = models.CharField(
        max_length=256, null=True, blank=True, help_text='The MIMEType of the file')

    def __str__(self):
        return str(self.incident_id)

jhpl_ims/forms.py
from django import forms
from django.forms import ModelForm, Textarea
from jhpl_ims.models import jhpl_ims_masterlist, incident
from tempus_dominus.widgets import DateTimePicker
from django.core.files.uploadedfile import InMemoryUploadedFile
from jhpl_ims.humanize import naturalsize


class CommentForm(forms.Form):
    comment = forms.CharField()


class MasterListForm(forms.ModelForm):
    class Meta:
        model = jhpl_ims_masterlist
        exclude = ["owner"]

        widgets = {
            'doc_num': forms.TextInput(attrs={'class': 'form-control'}),
            'doc_title': forms.TextInput(attrs={'class': 'form-control'}),
            'rev_num': forms.NumberInput(attrs={'class': 'form-control'}),
            'issue_date': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'status': forms.Select(attrs={'class': 'form-control'}),
            'reviewed_by': forms.Select(attrs={'class': 'form-control'}),
            'reviewed_date': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'approved_by': forms.Select(attrs={'class': 'form-control'}),
            'approved_date': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'control_copy_num': forms.NumberInput(attrs={'class': 'form-control'}),
        }



# Create the form class.
class CreateForm(forms.ModelForm):
    max_upload_limit = 2 * 1024 * 1024
    max_upload_limit_text = naturalsize(max_upload_limit)

    # Call this 'picture' so it gets copied from the form to the in-memory model
    # It will not be the "bytes", it will be the "InMemoryUploadedFile"
    # because we need to pull out things like content_type
    picture = forms.FileField(required=False, label='File to Upload <= '+max_upload_limit_text)
    upload_field_name = 'picture'

    # Hint: this will need to be changed for use in the ads application :)
    class Meta:
        model = incident
        fields = ['incident_datetime','people_involved','incident_location','incident_description','incident_witness','picture']  # Picture is manual
        widgets = {
            'incident_datetime': forms.DateTimeInput(attrs={'type': 'datetime-local', 'class': 'form-control'}),
        }
    # Validate the size of the picture
    def clean(self):
        cleaned_data = super().clean()
        pic = cleaned_data.get('picture')
        if pic is None:
            return
        if len(pic) > self.max_upload_limit:
            self.add_error('picture', "File must be < "+self.max_upload_limit_text+" bytes")

    # Convert uploaded File object to a picture
    def save(self, commit=True):
        instance = super(CreateForm, self).save(commit=False)

        # We only need to adjust picture if it is a freshly uploaded file
        f = instance.picture   # Make a copy
        if isinstance(f, InMemoryUploadedFile):  # Extract data from the form to the model
            bytearr = f.read()
            instance.content_type = f.content_type
            instance.picture = bytearr  # Overwrite with the actual image data

        if commit:
            instance.save()
       

        return instance

jhpl_ims/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import View
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import UpdateView, DeleteView
from django.shortcuts import redirect, get_object_or_404
from jhpl_ims.forms import CommentForm, MasterListForm,CreateForm
from jhpl_ims.owner import OwnerDeleteView,OwnerListView, OwnerDetailView, OwnerDeleteView
from django.views.generic.edit import DeleteView
# Create your views here.
from . models import jhpl_ims_masterlist, notes,incident
from django.contrib.auth import get_user_model
from django.contrib.humanize.templatetags.humanize import naturaltime


class index(LoginRequiredMixin, View):
    def get(self, request):
        master_list = jhpl_ims_masterlist.objects.all()
        show_edit_link = False

        if request.user.username in ["admin", "admin2"]:
            show_edit_link = True

        ctx = {'master_list': master_list, 'show_edit_link': show_edit_link}
        return render(request, 'jhpl_ims/index.html', ctx)


class procedures(LoginRequiredMixin, View):
    def get(self, request, pk):
        master_list = jhpl_ims_masterlist.objects.filter(ims_masterlist_id=pk)
        notes_list = notes.objects.filter(
            jhpl_ims_masterlist_key=pk).order_by('-updated_at')
        comment_form = CommentForm()
        ctx = {'master_list': master_list,
               'notes_list': notes_list, 'comment_form': comment_form}
        if pk == 1:
            return render(request, 'jhpl_ims/sop_one.html', ctx)
        elif pk == 2:
            return render(request, 'jhpl_ims/sop_two.html', ctx)
        elif pk == 3:
            return render(request, 'jhpl_ims/sop_three.html', ctx)
        elif pk == 4:
            return render(request, 'jhpl_ims/sop_four.html', ctx)
        elif pk == 5:
            return render(request, 'jhpl_ims/sop_five.html', ctx)


# class MasterUpdateView(LoginRequiredMixin, View):
#     model = jhpl_ims_masterlist
#     fields = ['doc_num', 'doc_title', 'rev_num', 'issue_date', 'status','approved_by','approved_date','reviewed_by','reviewed_date','control_copy_num']
#     fields_exclude = ['ims_masterlist_id', 'owner', 'created_at', 'updated_at']

class MasterUpdateView(LoginRequiredMixin, View):
    model = jhpl_ims_masterlist
    success_url = reverse_lazy('jhpl_ims/index.html')
    template = 'jhpl_ims/jhpl_ims_masterlist_form.html'

    def get(self, request, pk):
        masterlist = get_object_or_404(self.model, pk=pk)
        form = MasterListForm(instance=masterlist)
        ctx = {'form': form}
        return render(request, self.template, ctx)

    def post(self, request, pk):
        masterlist = get_object_or_404(self.model, pk=pk)
        form = MasterListForm(request.POST, instance=masterlist)
        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template, ctx)

        form.save()
        return redirect(self.success_url)


class NotesCreateView(LoginRequiredMixin, View):
    def post(self, request, pk):
        key = get_object_or_404(jhpl_ims_masterlist, ims_masterlist_id=pk)
        Notes = notes(
            large_text_body=request.POST['comment'], owner=request.user, jhpl_ims_masterlist_key=key)
        Notes.save()
        return redirect(reverse('jhpl_ims:procedures', args=[key.pk]))


class NotesDeleteView(OwnerDeleteView):
    model = notes
    template_name = "jhpl_ims/notes_delete.html"

    def get_success_url(self):
        jhpl_ims_masterlist_key = self.object.jhpl_ims_masterlist_key
        return reverse('jhpl_ims:procedures', args=[jhpl_ims_masterlist_key.ims_masterlist_id])


class IncidentListView(OwnerListView):
    model = incident
    template_name = "jhpl_ims/incident_list.html"

    def get(self, request) :
        incident_list = incident.objects.all()
        show_edit_link = False
        
        if request.user.username in ["admin", "admin2"]:
            show_edit_link = True
      
        ctx = {'incident_list' : incident_list,'show_edit_link' : show_edit_link}
        return render(request, self.template_name, ctx)


class IncidentDetailView(OwnerDetailView):
    model = incident
    template_name = "jhpl_ims/incident_detail.html"
    
    def get(self, request, pk):
        x = incident.objects.get(incident_id=pk)
        context = { 'incident' : x }
        return render(request, self.template_name, context)
    
    
class IncidentDeleteView(DeleteView):
    model = incident


class IncidentCreateView(LoginRequiredMixin,View):
    template_name = 'jhpl_ims/incident_form.html'
    success_url = reverse_lazy('jhpl_ims:incident_list')

    def get(self, request, pk=None):
        form = CreateForm()
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        form = CreateForm(request.POST, request.FILES or None)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        # Add owner to the model before saving
        incident = form.save(commit=False)
        incident.owner = self.request.user
        incident.save()
        return redirect(self.success_url)
    

class IncidentUpdateView(LoginRequiredMixin, View):
    model = incident
    template_name = 'jhpl_ims/incident_form.html'
    success_url = reverse_lazy('jhpl_ims:incident_list')

    def get(self, request, pk):
        incident = get_object_or_404(self.model, incident_id=pk)
        
        form = CreateForm(instance=incident)
        ctx = {'form': form}
        return render(request, self.template_name, ctx)
    
    def post(self, request, pk=None):
        incident = get_object_or_404(self.model, incident_id=pk, owner=self.request.user)
        print(incident.owner)
        form = CreateForm(request.POST, request.FILES or None, instance=incident)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        incident = form.save(commit=False)
        incident.save()
        return redirect(self.success_url)
    
    
def stream_file(request, pk):
    from jhpl_ims.models import incident
    incident = get_object_or_404(incident, incident_id=pk)
    response = HttpResponse()
    response['Content-Type'] = incident.content_type
    response['Content-Length'] = len(incident.picture)
    response.write(incident.picture)
    return response

jhpl_ims/templates/jhpl_ims/incident_confirm_delete.html
{% extends "base_menu.html" %} {% block content %}

<h1>Delete Make</h1>
<p>Are you sure you want to delete the incident:</p>
<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete." />
  <input
    type="submit"
    onclick="window.location='{% url 'jhpl_ims:incident_list' %}' ; return false;"
    value="Cancel"
  />
</form>

{% endblock %}

jhpl_ims/templates/jhpl_ims/incident_detail.html
{% extends "base_menu.html" %} {% load humanize %}
<!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->
{% block head %}
<style>
  .overlay {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: 10;
    display: none;
    background-color: rgba(0, 0, 0, 0.5); /*dim the background*/
  }
</style>
{% endblock %} {% block content %} {% if incident.content_type %}
<div
  id="overlay"
  class="overlay"
  style="text-align: center"
  onclick="document.getElementById('overlay').style.display = 'none';"
>
  <img
    style="width: 90%; margin-top: 50px; border: 3px solid black"
    src="{% url 'jhpl_ims:incident_picture' incident.incident_id %}"
  />
</div>
{% endif %} {% if user == incident.owner %}
<span style="float: right">
  ({{ incident.updated_at|naturaltime }})

  <a href="{% url 'jhpl_ims:incident_update' incident.incident_id %}"
    ><i class="fa fa-pencil"></i
  ></a>
  <a href="{% url 'jhpl_ims:incident_delete' incident.incident_id %}"
    ><i class="fa fa-trash"></i
  ></a>
</span>
{% endif %}

<h3><b>Incident Number:</b> {{ incident.incident_id }}</h3>
<hr />
{% if incident.content_type %}
<img
  style="float: right; max-width: 50%"
  src="{% url 'jhpl_ims:incident_picture' incident.incident_id %}"
  onclick="document.getElementById('overlay').style.display = 'block';"
/>
{% endif %}
<h4><b>Reported By:</b> {{ incident.owner }}</h4>
<h4><b>Report Date:</b> {{ incident.created_at|date }}</h4>
<h4><b>Incident Date Time:</b> {{ incident.incident_datetime }}</h4>
<h4><b>People Involved:</b> {{ incident.people_involved }}</h4>
<h4><b>Incident Location:</b> {{ incident.incident_location }}</h4>
<h4><b>Witness: </b>{{ incident.incident_witness }}</h4>
<hr />
<h3><b>Incident Description</b></h3>
<p>{{incident.incident_description}}</p>

<p>
  <a href="{% url 'jhpl_ims:incident_list' %}">Go Back</a>
</p>
{% endblock %}

jhpl_ims/templates/jhpl_ims/incident_list.html
{% extends "base_menu.html" %} {% block content %}

<title>Incident Reports</title>
<style>
  table {
    width: 100%;
    border-collapse: collapse;
  }

  th,
  td {
    border: 1px solid #ddd;
    padding: 8px;
  }

  th {
    background-color: #f2f2f2;
    color: black;
  }

  input {
    margin-bottom: 10px;
  }

  back {
  }
</style>

<h1>Incident Logs, Welcome <b>{{user.username}}</b></h1>

<input
  type="text"
  id="searchInput"
  onkeyup="filterFunction()"
  placeholder="Search by location..."
/>
<p id="back"></p>

<a href="{% url 'jhpl_ims:incident_create' %}"> Report Incidents Here </a>
| Click on <b>Incident Number</b> To Visit Incident |
<a href="/"> Click Here To Go Back </a>

<table id="documentTable">
  <thead>
    <tr>
      <th>Incident Number</th>
      <th>Reported By</th>
      <th>Report Date</th>
      <th>Incident Date Time</th>
      <th>People Involved</th>
      <th>Incident Location</th>
      <th>Witness</th>
      {% if show_edit_link %}
      <th>Admin Area</th>
      {% endif %}
    </tr>
  </thead>
  <tbody>
    <!-- Sample row: you will need to add more rows and data -->
    {% for incident in incident_list %} {% if show_edit_link %}

    <tr>
      <td>
        <a href="{% url 'jhpl_ims:incident_detail' incident.incident_id %}"
          >{{incident.incident_id}}</a
        >
      </td>
      <td>{{incident.owner}}</td>
      <td>{{incident.created_at}}</td>
      <td>{{incident.incident_datetime}}</td>
      <td>{{incident.people_involved}}</td>
      <td>{{incident.incident_location}}</td>
      <td>{{incident.incident_witness}}</td>

      <td>
        <a href="{% url 'jhpl_ims:incident_delete' incident.incident_id %}"
          >Delete</a
        >
      </td>
    </tr>

    {% elif user == incident.owner %}

    <tr>
      <td>
        <a href="{% url 'jhpl_ims:incident_detail' incident.incident_id %}"
          >{{incident.incident_id}}</a
        >
      </td>
      <td>{{incident.owner}}</td>
      <td>{{incident.created_at}}</td>
      <td>{{incident.incident_datetime}}</td>
      <td>{{incident.people_involved}}</td>
      <td>{{incident.incident_location}}</td>
      <td>{{incident.incident_witness}}</td>
    </tr>

    {% else %}
    <td>No Data</td>
    {% endif %} {% endfor %}
  </tbody>
</table>

<script>
  function filterFunction() {
    let input, filter, table, tr, td, i, txtValue;
    input = document.getElementById("searchInput");
    filter = input.value.toUpperCase();
    table = document.getElementById("documentTable");
    tr = table.getElementsByTagName("tr");
    for (i = 0; i < tr.length; i++) {
      td = tr[i].getElementsByTagName("td")[5]; // Change index as needed
      if (td) {
        txtValue = td.textContent || td.innerText;
        if (txtValue.toUpperCase().indexOf(filter) > -1) {
          tr[i].style.display = "";
        } else {
          tr[i].style.display = "none";
        }
      }
    }
  }
</script>

{% endblock %}

jhpl_ims/templates/jhpl_ims/notes_delete.html
{% extends "base_menu.html" %} {% block content %}

<h1>Delete Comment</h1>

<p>Are you sure you want to delete</p>
<p>{{notes}}</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" class="btn btn-primary" value="Yes, delete." />
  <a
    href="{% url 'jhpl_ims:procedures' notes.jhpl_ims_masterlist_key.ims_masterlist_id %}"
    class="btn btn-secondary"
    >Cancel</a
  >
</form>

{% endblock %}

jhpl_ims/templates/jhpl_ims/sop_five.html
<!DOCTYPE html>
{% extends "base_menu.html" %} {% load crispy_forms_tags %}
{% load humanize %} 
{% block content %}

<style>
  .header {
    display: flex;
    justify-content: space-between;
    padding: 20px;
    background: linear-gradient(
      90deg,
      #005f73 0%,
      #3c6997 25%,
      #a5c7b9 50%,
      #184e77 75%,
      #1f7a8c 100%
    );
    color: white;
    border-bottom: 1px solid #ddd;
  }
  .header-item {
    flex: 1;
    margin-right: 20px;
  }
  .header-item:last-child {
    margin-right: 0;
  }
</style>

{% if master_list %} {% for master in master_list %}
<header class="header">
  <div class="header-item">
    <p><b>Document Number:</b> {{master.doc_num}} <span id="docNo"></span></p>
    <p><b>Issue Date:</b> {{master.issue_date}} <span id="issueDate"></span></p>
    <p><b>Status:</b> {{master.status}} <span id="issueStatus"></span></p>
  </div>
  <div class="header-item">
    <p><b>Revision No: </b>{{master.rev_num}}<span id="revNo"></span></p>
    <p><b>Controlled Copy No:</b> {{master.control_copy_num}} <span id="controlCopyNo"></span></p>
    <p><b>Status:</b> {{master.status}} <span id="issueDate"></span></p>
  </div>
  <div class="header-item">
    <p><b>Approval</b></p>
    <p><b>Name:</b> {{master.approved_by}} <span id="approvedBy"></span></p>
    <p><b>Date:</b> {{master.approved_date}} <span id="approvalDate"></span></p>
  </div>
  <div class="header-item">
    <p><b>Review</b></p>
    <p><b>Name: </b> {{master.reviewed_by}} <span id="reviewedBy"></span></p>
    <p><b> Date: </b> {{master.reviewed_date}} <span id="reviewDate"></span></p>
  </div>
</header>

<main>
  <h2><b>{{ master.doc_title }}</b></h2>

  <h3>This is our {{master.ims_masterlist_id}}th procedure</h3>

  <p id="docContent"></p>
</main>

<p><a href="{% url 'jhpl_ims:index' %}">Go Back</a></p>

{% if user.is_authenticated %}
<p id="back"> You are logged in as <b>{{user.username}} </b>
<br clear="all"/>
<form method="post" action="{% url 'jhpl_ims:comment_create' master.ims_masterlist_id %}">
    {% csrf_token %}
    {{ comment_form|crispy }}
<input type="submit" value="Submit">
<input type="submit" value="Cancel" onclick="window.location.href='{% url 'jhpl_ims:procedures' master.ims_masterlist_id %}';return false;">
</form>
</p>
{% endif %}


<h4><b>Notes: </b></h4>
<hr />
{% if notes_list%}
{% for comment in notes_list %}
<p><b>Owner: </b>{{comment.owner}} | {{comment.updated_at|naturaltime}}</p>
<p><b>Comments: </b>{{comment.large_text_body}}
{% if user == comment.owner %}
<a href="{% url 'jhpl_ims:comment_delete' comment.notes_id %}"><i class="fa fa-trash"></i></a>
</p>
{% endif %}
<hr />
{% endfor %}
{% endif %}
</p>


{% endfor %}
{% endif %}

{% endblock %}

jhpl_ims/templates/jhpl_ims/sop_four.html
<!DOCTYPE html>
{% extends "base_menu.html" %} {% load crispy_forms_tags %}
{% load humanize %} 
{% block content %}

<style>
  .header {
    display: flex;
    justify-content: space-between;
    padding: 20px;
    background: linear-gradient(
      90deg,
      #005f73 0%,
      #3c6997 25%,
      #a5c7b9 50%,
      #184e77 75%,
      #1f7a8c 100%
    );
    color: white;
    border-bottom: 1px solid #ddd;
  }
  .header-item {
    flex: 1;
    margin-right: 20px;
  }
  .header-item:last-child {
    margin-right: 0;
  }
</style>

{% if master_list %} {% for master in master_list %}
<header class="header">
  <div class="header-item">
    <p><b>Document Number:</b> {{master.doc_num}} <span id="docNo"></span></p>
    <p><b>Issue Date:</b> {{master.issue_date}} <span id="issueDate"></span></p>
    <p><b>Status:</b> {{master.status}} <span id="issueDate"></span></p>
  </div>
  <div class="header-item">
    <p><b>Revision No: </b>{{master.rev_num}}<span id="revNo"></span></p>
    <p><b>Controlled Copy No:</b> {{master.control_copy_num}} <span id="controlCopyNo"></span></p>
  </div>
  <div class="header-item">
    <p><b>Approval</b></p>
    <p><b>Name:</b> {{master.approved_by}} <span id="approvedBy"></span></p>
    <p><b>Date:</b> {{master.approved_date}} <span id="approvalDate"></span></p>
  </div>
  <div class="header-item">
    <p><b>Review</b></p>
    <p><b>Name: </b> {{master.reviewed_by}} <span id="reviewedBy"></span></p>
    <p><b> Date: </b> {{master.reviewed_date}} <span id="reviewDate"></span></p>
  </div>
</header>

<main>
  <h2><b>{{ master.doc_title }}</b></h2>

  <h3>This is our {{master.ims_masterlist_id}}th procedure</h3>

  <p id="docContent"></p>
</main>


<p><a href="{% url 'jhpl_ims:index' %}">Go Back</a></p>

{% if user.is_authenticated %}

<p id="back"> You are logged in as <b>{{user.username}} </b>
<br clear="all"/>
<form method="post" action="{% url 'jhpl_ims:comment_create' master.ims_masterlist_id %}">
    {% csrf_token %}
    {{ comment_form|crispy }}
<input type="submit" value="Submit">
<input type="submit" value="Cancel" onclick="window.location.href='{% url 'jhpl_ims:procedures' master.ims_masterlist_id %}';return false;">
</form>
</p>
{% endif %}


<h4><b>Notes: </b></h4>
<hr />
{% if notes_list%}
{% for comment in notes_list %}
<p><b>Owner: </b>{{comment.owner}} | {{comment.updated_at|naturaltime}}</p>
<p><b>Comments: </b>{{comment.large_text_body}}
{% if user == comment.owner %}
<a href="{% url 'jhpl_ims:comment_delete' comment.notes_id %}"><i class="fa fa-trash"></i></a>
</p>
{% endif %}
<hr />
{% endfor %}
{% endif %}
</p>

{% endfor %}
{% endif %}

{% endblock %}